apiVersion: v1
kind: Service
metadata:
  namespace: project-plato
  name: db1
spec:
  selector:
    app: db1
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  namespace: project-plato
  name: db2
spec:
  selector:
    app: db2
  ports:
  - port: 5432
    targetPort: 5432
